### ISSUE TITLE
Como faz para ver o site?

### ISSUE THREAD

**Issue by lucasbabur** [GustavoTxFreitas/react-vigenere-cipher#1]
Fala Gustavo, então, como faz para ver o seu site? Sou novo aqui no Github.

**Comment by GustavoTxFreitas-zz** [comment]
Boa tarde, Lucas!

Estou trabalhando em alterações para a apresentação do projeto. Logo, será possível visitar o site por um link disponível no Read.Me!

Peço que continue aguardando, entrarei em contato após a nova atualização.

Att.
Gustavo Teixeira.
